resolver: lts-4.1
packages:
  - '.'
  - location:
      git: https://github.com/krdlab/haskell-oidc-client.git
      commit: 4861c428b73c72567eee0a91e7e29122643a1842
    extra-dep: true
  - location:
      git: https://github.com/bos/hdbc-mysql.git
      commit: d43ea057019ff683f278f36af410f4d3cbc731bc
    extra-dep: true
  - location:
      git: https://github.com/krdlab/haskell-relational-record.git
      commit: e19db59c09f348fee63e3ffec2ef60b0e193d7ad
    subdirs:
      - relational-query
    extra-dep: true
extra-deps:
  - servant-lucid-0.4.4.5
  - oidc-client-0.2.0.0
  - jose-jwt-0.7
  - base32-bytestring-0.2.1.0
  - bits-extras-0.1.3
  - HDBC-mysql-0.6.6.2
  - HDBC-session-0.1.0.0
  - names-th-0.2.0.1
  - persistable-record-0.3.0.0
  - relational-query-0.8.0.4
  - relational-query-HDBC-0.5.0.0
  - relational-record-0.1.2.0
  - relational-schemas-0.1.2.2
  - sql-words-0.1.3.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
